add ble_lywsd03mmc
adafruit/Adafruit_CircuitPython_Bundle pull request #295
Opened 2021-02-12 21:33 UTC by dhalbert

BLE support for Xiaomi thermometer/hygrometer. This is for the factory firmware. There is also an open-source firmware load ("ATC")  that will be a separate library.
https://www.adafruit.com/product/4881. Not yet in stock, but others found this library and are using it with their separately-purchased sensors, so we should release it.

2021-02-13 00:02 UTC, askpatrickw approved these changes
This looks identical to other add module merges with the exception of the lack of a docs link. I assume the docs will come when the product releases, so approving.

2021-02-16 15:10 UTC, kattni requested changes
@dhalbert You need to add this to the library list in the docs folder. Take a look at it to get the format needed. Please let me know if you need assistance.

2021-02-16 16:05 UTC, dhalbert commented
@kattni Thanks for reminding me. I also removed the word "Service" from a few other libs in there, because the libraries are not really just "Services", or what they are supporting is not exactly a Service.

2021-02-16 16:11 UTC, kattni approved these changes

2021-02-16 16:11 UTC, kattni commented
Thanks @dhalbert!

2021-02-16 16:11 UTC, merged