Some small pointers on library devleopment
adafruit/Adafruit_CircuitPython_Bundle pull request #379
Opened 2022-05-02 20:29 UTC by davclark

- Added a LIBRARY_DEVELOPMENT.rst doc in the root
- Added a mention of this doc in the README.rst

This is just intended as a starting point, you are welcome to change or dispose of it as you please!

2022-05-02 21:26 UTC, FoamyGuy commented
For some reason the actions seems to be running against an older commit rather than the most recent one. It's failing due to end of file newline in the new rst file. But as far as I can tell that was fixed int he latest commit so I'm not really sure why it didn't pass

2022-05-02 22:19 UTC, dhalbert requested changes

2022-05-02 22:19 UTC, dhalbert commented on LIBRARY_DEVELOPMENT.rst
> +
Still a blank line here, causing pre-commit failure. The previous file had two blank lines.

2022-11-09 17:34 UTC, jepler approved these changes
I updated the PR and fixed the whitespace problem.

2022-11-09 17:34 UTC, merged